Fix readthedoc/API reference
tomography/tomocupy-cli pull request #43
Opened 2023-06-07 14:43 UTC by decarlof

- fixes [this](https://tomocupy.readthedocs.io/en/latest/api/tomocupy.find_center.html) issue 
- adds missing bib references
- clear all readthedocs build warnings

2023-06-09 20:25 UTC, decarlof commented
@nikitinvv can we delete writer_nolinks.py? Is not used anywhere and the h5nolinks option is handled in writer.py

2023-06-09 21:24 UTC, nikitinvv requested changes

2023-06-09 21:24 UTC, nikitinvv commented on docs/source/conf.py
>      'pytorch_wavelets',
Could you remove pytorch_wavelets and torch from dependencies (and maybe synchronize the deps from setup.py file)? I have rewritten all torch fucntions with cupy and now we dont need these dependencies.

2023-06-09 21:25 UTC, nikitinvv commented
> @nikitinvv can we delete writer_nolinks.py? Is not used anywhere and the h5nolinks option is handled in writer.py

Yes, sure

2023-06-12 22:02 UTC, decarlof commented
@nikitinvv done and ready for you to merge

2023-06-12 22:09 UTC, nikitinvv commented
thanks @decarlof

2023-06-12 22:09 UTC, merged